# Generated by Django 4.2.2 on 2023-06-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_good_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
