# Generated by Django 4.2.2 on 2023-06-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_good_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
